package PersonaApp;

/**
* PersonaApp/PersonaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* lunes 22 de abril de 2019 07:27:27 PM COT
*/

public final class PersonaHolder implements org.omg.CORBA.portable.Streamable
{
  public PersonaApp.Persona value = null;

  public PersonaHolder ()
  {
  }

  public PersonaHolder (PersonaApp.Persona initialValue)
  {
    value = initialValue;
  }

  @Override
  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PersonaApp.PersonaHelper.read (i);
  }

  @Override
  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PersonaApp.PersonaHelper.write (o, value);
  }

  @Override
  public org.omg.CORBA.TypeCode _type ()
  {
    return PersonaApp.PersonaHelper.type ();
  }

}
